name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: fitbit-importer-linux-amd64
            setup_cmd: |
              sudo apt-get update
              sudo apt-get install -y libgl1-mesa-dev xorg-dev
          - os: windows-latest
            name: fitbit-importer-windows-amd64.exe
            setup_cmd: echo "Windows setup complete"
            
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install dependencies
      run: ${{ matrix.setup_cmd }}
        
    - name: Build binary
      run: go build -o ${{ matrix.name }} cmd/main.go
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: '**/*'
        generate_release_notes: true
        body: |
          ## Cross-platform binaries
          - **Linux (amd64)**: `fitbit-importer-linux-amd64`
          - **Windows (amd64)**: `fitbit-importer-windows-amd64.exe`