name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: fitbit-importer-linux-amd64
          - os: windows-latest
            name: fitbit-importer-windows-amd64.exe
            
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
        
    - name: Build binary
      run: go build -o ${{ matrix.name }} cmd/main.go
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: fitbit-importer-linux-amd64
        path: ./dist/
        
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: fitbit-importer-windows-amd64.exe
        path: ./dist/
      
    - name: List files
      run: ls -la dist/
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
        body: |
          ## Cross-platform binaries
          - **Linux (amd64)**: `fitbit-importer-linux-amd64`
          - **Windows (amd64)**: `fitbit-importer-windows-amd64.exe`