name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build binaries
      run: |
        mkdir -p dist
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -o dist/fitbit-importer-linux-amd64 cmd/main.go
        GOOS=linux GOARCH=arm64 go build -o dist/fitbit-importer-linux-arm64 cmd/main.go
        GOOS=windows GOARCH=amd64 go build -o dist/fitbit-importer-windows-amd64.exe cmd/main.go
        GOOS=darwin GOARCH=amd64 go build -o dist/fitbit-importer-darwin-amd64 cmd/main.go
        GOOS=darwin GOARCH=arm64 go build -o dist/fitbit-importer-darwin-arm64 cmd/main.go
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true