name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib gcc-mingw-w64 libgl1-mesa-dev xorg-dev
        
    - name: Build binaries
      run: |
        mkdir -p dist
        # Build for Linux (native)
        GOOS=linux GOARCH=amd64 go build -o dist/fitbit-importer-linux-amd64 cmd/main.go
        # Build for Windows (cross-compile with mingw)
        CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -o dist/fitbit-importer-windows-amd64.exe cmd/main.go
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true