name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
        
    - name: Build Linux binary
      run: |
        mkdir -p dist
        go build -o dist/fitbit-importer-linux-amd64 cmd/main.go
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
        body: |
          ## Cross-platform binaries
          - Linux (amd64): fitbit-importer-linux-amd64
          
          For Windows and macOS builds, please build from source using:
          ```bash
          git clone https://github.com/timgrote/fitbitImporter.git
          cd fitbitImporter
          go build cmd/main.go
          ```