name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev
        
    - name: Build Linux binary
      run: go build -o fitbit-importer-linux-amd64 cmd/main.go
      
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-binary
        path: fitbit-importer-linux-amd64

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install Windows dependencies
      run: |
        choco install tdm-gcc
        go mod download
        
    - name: Build Windows binary
      run: go build -o fitbit-importer-windows-amd64.exe cmd/main.go
      
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-binary
        path: fitbit-importer-windows-amd64.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: linux-binary
        
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-binary
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          fitbit-importer-linux-amd64
          fitbit-importer-windows-amd64.exe
        generate_release_notes: true
        body: |
          ## Cross-platform binaries
          - **Linux (amd64)**: `fitbit-importer-linux-amd64`
          - **Windows (amd64)**: `fitbit-importer-windows-amd64.exe`